# commands relative to root of current git repository
alias cdg='cd "$(git rev-parse --show-cdup)"'
alias lsg='ls "$(git rev-parse --show-cdup)"'

# enable vi mode
set -o vi

# git completion
source ~/.git-completion.bash
source ~/.git-prompt.sh

# git prompt
export GIT_PS1_SHOWDIRTYSTATE="true"
export GIT_PS1_SHOWUNTRACKEDFILES="true"
export GIT_PS1_SHOWUPSTREAM="auto"
export PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
